### ISSUE TITLE
TeamSpace: Sticky TabHeader improvements

### ISSUE THREAD

**Issue by jocelynmutso** [digiexpress-io/digiexpress-parent#165]
**Task C: Sticky TabHeader**

The styles/formatting here need some help.

- [x] Tabs should show the number of tasks in that group.
- [x] It would look a lot better if there was no visible gap between the top of the TabHeader box and the bottom of the actual application tabs.
- [x] It would be ideal if the content would physically cut off BEFORE it scrolls under the TabHeader.
- [x] The tab header box itself doesn't look good, so better styling needs to be devised.
